spring:
    profiles:
        active:
        - dev
---
server:
    port: 8201
spring:
    profiles: dev   #开发环境
    application:
        name: spring-cloud-micro-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 
---
server:
    port: 8202
spring:
    profiles: test   #开发环境
    application:
        name: spring-cloud-micro-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 
---

